### ISSUE TITLE
Config error

### ISSUE THREAD

**Issue by MikeVL** [agschwender/pilbox#32]
My config file:

```
# General settings
port = 8888

# Set default saving options
format = None
optimize = 1
quality = 80
```

Error:
```
root@698a4fd0d906:/# pilbox --config=pilbox.conf
Traceback (most recent call last):
  File "/usr/local/bin/pilbox", line 9, in <module>
    load_entry_point('pilbox==1.1.6', 'console_scripts', 'pilbox')()
  File "/usr/local/lib/python3.4/site-packages/pilbox/app.py", line 332, in main
    parse_command_line()
  File "/usr/local/lib/python3.4/site-packages/pilbox/app.py", line 314, in parse_command_line
    tornado.options.parse_command_line()
  File "/usr/local/lib/python3.4/site-packages/tornado/options.py", line 525, in parse_command_line
    return options.parse_command_line(args, final=final)
  File "/usr/local/lib/python3.4/site-packages/tornado/options.py", line 261, in parse_command_line
    option.parse(value)
  File "/usr/local/lib/python3.4/site-packages/tornado/options.py", line 417, in parse
    self.callback(self._value)
  File "/usr/local/lib/python3.4/site-packages/pilbox/app.py", line 48, in <lambda>
    callback=lambda path: parse_config_file(path, final=False))
  File "/usr/local/lib/python3.4/site-packages/tornado/options.py", line 533, in parse_config_file
    return options.parse_config_file(path, final=final)
  File "/usr/local/lib/python3.4/site-packages/tornado/options.py", line 280, in parse_config_file
    self._options[name].set(config[name])
  File "/usr/local/lib/python3.4/site-packages/tornado/options.py", line 432, in set
    (self.name, self.type.__name__, type(value)))
tornado.options.Error: Option 'quality' is required to be a str (<class 'int'> given)
```

**Comment by MikeVL** [comment]
Also timeout error
```
Traceback (most recent call last):
  File "/usr/local/bin/pilbox", line 9, in <module>
    load_entry_point('pilbox==1.1.6', 'console_scripts', 'pilbox')()
  File "/usr/local/lib/python3.4/site-packages/pilbox-1.1.6-py3.4.egg/pilbox/app.py", line 332, in main
    parse_command_line()
  File "/usr/local/lib/python3.4/site-packages/pilbox-1.1.6-py3.4.egg/pilbox/app.py", line 314, in parse_command_line
    tornado.options.parse_command_line()
  File "/usr/local/lib/python3.4/site-packages/tornado-4.0.2-py3.4-linux-x86_64.egg/tornado/options.py", line 525, in parse_command_line
    return options.parse_command_line(args, final=final)
  File "/usr/local/lib/python3.4/site-packages/tornado-4.0.2-py3.4-linux-x86_64.egg/tornado/options.py", line 261, in parse_command_line
    option.parse(value)
  File "/usr/local/lib/python3.4/site-packages/tornado-4.0.2-py3.4-linux-x86_64.egg/tornado/options.py", line 417, in parse
    self.callback(self._value)
  File "/usr/local/lib/python3.4/site-packages/pilbox-1.1.6-py3.4.egg/pilbox/app.py", line 48, in <lambda>
    callback=lambda path: parse_config_file(path, final=False))
  File "/usr/local/lib/python3.4/site-packages/tornado-4.0.2-py3.4-linux-x86_64.egg/tornado/options.py", line 533, in parse_config_file
    return options.parse_config_file(path, final=final)
  File "/usr/local/lib/python3.4/site-packages/tornado-4.0.2-py3.4-linux-x86_64.egg/tornado/options.py", line 280, in parse_config_file
    self._options[name].set(config[name])
  File "/usr/local/lib/python3.4/site-packages/tornado-4.0.2-py3.4-linux-x86_64.egg/tornado/options.py", line 432, in set
    (self.name, self.type.__name__, type(value)))
tornado.options.Error: Option 'timeout' is required to be a float (<class 'int'> given)
```

**Comment by xtagon** [comment]
Try the following settings:

```python
# General settings
port = 8888

# Set default saving options
format = None
optimize = "1"
quality = "80"
timeout = 10.0 # Or whatever you want your timeout to be, just make it a float
```

The config options expect strings except for `port` which should be an integer and `timeout` which should be a float.

**Comment by MikeVL** [comment]
Maybe to fix it docs: https://github.com/agschwender/pilbox#configuration ?

**Comment by agschwender** [comment]
Thanks for responding @xtagon. Yes, `quality` is a `string` because it supports values of `1-100` and `keep`.  `timeout` is a `float` because it's what tornado requires. `optimize` should be fine as an integer though. In any case, I updated the README and sample configuration to reflect the correct data type for `quality`.
