### ISSUE TITLE
Uwsgi support question.

### ISSUE THREAD

**Issue by firebait** [agschwender/pilbox#48]
Hi I've been trying to run pilbox on elastic beanstalk I got pretty close to it but I'm stuck with some async issue.

Here is the code I have so far:

```
#!/usr/bin/env python

import tornado.wsgi
from pilbox.app import PilboxApplication, main, options

options.port = 80
options.implicit_base_url = 'http://someurl'
uwsgi_adapter = tornado.wsgi.WSGIAdapter(PilboxApplication())
application = tornado.wsgi.WSGIContainer(uwsgi_adapter)


if __name__ == "__main__":
    main(application)
```

This starts the server correctly and it seems to do it's job but I get this error while running sending a request:

```
[E 151128 13:13:53 http1connection:53] Uncaught exception
    Traceback (most recent call last):
      File "/Users/marco/git/cc-pilbox/env/lib/python2.7/site-packages/tornado/http1connection.py", line 234, in _read_message
        delegate.finish()
      File "/Users/marco/git/cc-pilbox/env/lib/python2.7/site-packages/tornado/httpserver.py", line 280, in finish
        self.server.request_callback(self.request)
      File "/Users/marco/git/cc-pilbox/env/lib/python2.7/site-packages/tornado/wsgi.py", line 280, in __call__
        WSGIContainer.environ(request), start_response)
      File "/Users/marco/git/cc-pilbox/env/lib/python2.7/site-packages/tornado/wsgi.py", line 230, in __call__
        raise Exception("request did not finish synchronously")
    Exception: request did not finish synchronously
[I 151128 13:13:53 web:1811] 200 GET /?url=/thumbnail/28556751/4000&w=100&h=100&mode=crop (::1) 214.98ms
```

The reason I use the WSGIContainer is for local development but when submitting to elastic beanstalk I use the WSGIAdapter version. Any ideas would be great.

**Comment by agschwender** [comment]
From http://www.tornadoweb.org/en/stable/wsgi.html:

```In WSGI mode asynchronous methods are not supported. This means that it is not possible to use AsyncHTTPClient, or the tornado.auth or tornado.websocket modules.```

Pilbox uses `tornado.httpclient.AsyncHTTPClient` to make requests.
